from django.db import models


class Report(models.Model):
    """
    Model for storing reports generated by background jobs
    """
    title = models.CharField(max_length=200)
    report_type = models.CharField(
        max_length=50,
        choices=[
            ('sales', 'Sales Report'),
            ('inventory', 'Inventory Report'),
            ('user', 'User Report'),
        ]
    )
    data = models.JSONField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)

    class Meta:
        db_table = 'reports'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.title} - {self.report_type}"


class JobLog(models.Model):
    """
    Model for logging background job executions
    """
    job_name = models.CharField(max_length=200)
    status = models.CharField(
        max_length=20,
        choices=[
            ('pending', 'Pending'),
            ('running', 'Running'),
            ('completed', 'Completed'),
            ('failed', 'Failed'),
        ],
        default='pending'
    )
    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    error_message = models.TextField(null=True, blank=True)
    result = models.JSONField(null=True, blank=True)

    class Meta:
        db_table = 'job_logs'
        ordering = ['-started_at']

    def __str__(self):
        return f"{self.job_name} - {self.status}"
